### ISSUE TITLE
Error when running predict() using Spectral Mixture kernel

### ISSUE THREAD

**Issue by mpzapf** [marionmari/pyGPs#49]
Hello, I've been trying to use the Spectral Mixture kernel for a prediction (input: 10 dimensions, output: 1 dimension). However, the program throws the following error:
File "/usr/home/xyz/projects/GP/scripts/model_load_and_predict_pyGPs.py", line 97, in model_predict
    ymu, ys2, fmu, fs2, lp = model.predict(XY_test[:, :-1])
  File "/usr/local/lib/python2.7/dist-packages/pyGPs/Core/gp.py", line 412, in predict
    Fmu = np.tile(ms,(1,N)) + np.dot(Ks.T,alpha[nz])          # conditional mean fs|f
AttributeError: 'float' object has no attribute 'T'

The input data has the shape (276, 10) or similar in the first dimension.

Trying to build a model and predict using the RBF kernel on the same data set works without problems.

Could you please help me to resolve this issue or point me to possible casues of this error? Thank you in advance!

**Comment by mathDR** [comment]
Could you possibly post a minimal example that replicates your error?  From the look of the error, the covariance (Ks) seems to be 1x1.

**Comment by mpzapf** [comment]
Hello, thank you for your quick reply. Here is a minimal example based on the data in the attached zip/npz (reduced to 2 input dimensions and without standardizing the data, but the program still throwing the same error). 
Thank you in advance.

import numpy as np
import pyGPs

data = np.load('sample_data.npz')
X_train = data['X_train']
Y_train = data['Y_train']
X_test = data['X_test']

print(X_train)
print(Y_train)
print(X_test)

kernel = pyGPs.cov.SM()
m = pyGPs.mean.Zero()

model = pyGPs.GPR()
model.setData(X_train, Y_train)
model.setPrior(mean=m, kernel=kernel)

model.setOptimizer("Minimize", num_restarts=20)
model.getPosterior()
model.optimize()

ymu, ys2, fmu, fs2, lp = model.predict(X_test)




[sample_data.zip](https://github.com/marionmari/pyGPs/files/1276209/sample_data.zip)

**Comment by mathDR** [comment]
Hey @mpzapf I just pushed a PR that fixes some of the spectral mixture bugs.  The branch is spectral-mixture-bug.  Basically the multi-dimensional initialization of the kernel was never tested.  That, and a variable name in the predict method (id) is a protected name in python3, so i changed that too.

Note, that when using the SM kernel, you have to specify the number of components to use, along with the dimension of the data when initializing the kernel.  That, and due to the unique nature of the space that the kernel lives in, you should also run an initialization script for its hyperparameters given your data.

That said, the line
``` kernel = pyGPs.cov.SM()```
should read
```kernel = pyGPs.cov.SM(Q=3,D=X_train.shape[1])```
for three components.

Also, after setting the kernel and mean function, run
``` model.covfunc.initSMhypers(X_train, Y_train) ```
to "initialize" the hyperparameters of the covariance.

I will submit a merge request today, but in the meantime, just pull the branch to run.

Best

Dan

**Comment by mpzapf** [comment]
Hi Dan,
Thanks a lot for squashing the bugs and giving advice on the correct syntax. I'll pull the branch and check it out.

**Comment by mpzapf** [comment]
Hi Dan,
I've tried to run the minimal example (updated code posted below) with the pulled branch, however now I receive the following error:

```
import numpy as np
import pyGPs

data = np.load('sample_data.npz')
X_train = data['X_train']
Y_train = data['Y_train']
X_test = data['X_test']

print(X_train)
print(Y_train)
print(X_test)

kernel = pyGPs.cov.SM(Q=3,D=X_train.shape[1])
m = pyGPs.mean.Zero()

model = pyGPs.GPR()
model.setData(X_train, Y_train)
model.setPrior(mean=m, kernel=kernel)
model.covfunc.initSMhypers(X_train, Y_train)
model.setOptimizer("Minimize", num_restarts=20)
model.getPosterior()
model.optimize()

ymu, ys2, fmu, fs2, lp = model.predict(X_test)
```


File "/usr/home/xyz/projects/GP/scripts/minimal_example.py", line 19, in <module>
    model.covfunc.initSMhypers(X_train, Y_train)
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/cov.py", line 513, in initSMhypers
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
TypeError: 'float' object cannot be interpreted as an index

If I comment out the initSMhypers call, then I receive the following:

File "/usr/home/xyz/projects/GP/scripts/minimal_example.py", line 22, in <module>
    model.optimize()
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/gp.py", line 280, in optimize
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/opt.py", line 287, in findMin
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/opt.py", line 79, in _convert_to_array
ValueError: operands could not be broadcast together with shapes (0,) (15,) 

Could you please guide me on what's not working here? Thanks in advance.
Marc

**Comment by mathDR** [comment]
@mpzapf  The issue(s) were twofold:  One, there were infs in the hyperparameters.  I fixed that (can return only a large number, but not inf).  Also, the hyperparameters were not returning a list.  I fixed that too.  Try it now.

**Comment by mathDR** [comment]
@mpzapf Going forward, you might want to change the initialization method to something more robust.

**Comment by mpzapf** [comment]
@mathDR Thank you for fixing. I pulled the newest branch, however running the minimal example, this same error still persists:

> File "/usr/home/xyz/projects/GP/scripts/minimal_example.py", line 19, in <module>
>     model.covfunc.initSMhypers(X_train, Y_train)
>   File "build/bdist.linux-x86_64/egg/pyGPs/Core/cov.py", line 511, in initSMhypers
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2269, in amax
>     return amax(axis=axis, out=out, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
>     return umr_maximum(a, axis, None, out, keepdims)
> TypeError: 'float' object cannot be interpreted as an index

The other error (when running without hyperparameter init) is gone.

**Comment by mathDR** [comment]
@mpzapf I cannot replicate this error.  Could this be a python2 versus python3 issue?  The line (511)
```minshift = np.max(np.min(np.min(np.sqrt(d2))),1e-6)```
seems to be the culprit.  Can you determine what the issue is?

**Comment by mpzapf** [comment]
@mathDR I'm running Python2.7 and numpy 1.13

To my knowledge, np.max is equivalent to np.amax and does not take two numbers as in
`np.max(np.min(np.min(np.sqrt(d2))),1e-6)`
Is what you want to do here equivalent to 
`np.maximum(np.min(np.min(np.sqrt(d2))),1e-6)`
? Is the intention here to cap the minimum minshift at 1e-6 as well as the maximum maxshift at 1e-6?

Changing the code as above to np.maximum/np.minimum it runs till 
`hypinit[:Q] = np.log(w)`

and throws error:

> Traceback (most recent call last):
>   File "minimal_example.py", line 19, in <module>
>     model.covfunc.initSMhypers(X_train, Y_train)
>   File "/usr/home/xyz/Research_Packages/pyGPs/pyGPs/Core/cov.py", line 527, in initSMhypers
>     hypinit[:Q] = np.log(w)
> TypeError: can only assign an iterable

So I changed this part to:
`hypinit[:Q] = [np.log(w)] * Q`

After that, it throws the following:
```

> Traceback (most recent call last):
>   File "minimal_example.py", line 19, in <module>
>     model.covfunc.initSMhypers(X_train, Y_train)
>   File "/usr/home/xyz/Research_Packages/pyGPs/pyGPs/Core/cov.py", line 535, in initSMhypers
>     hypinit[Q + np.arange(0, Q * D)] = np.log(np.ndarray.flatten(m)).T
> TypeError: only integer scalar arrays can be converted to a scalar index

```

Therefore I modified from:
```
hypinit[Q + np.arange(0, Q * D)] = np.log(np.ndarray.flatten(m)).T
hypinit[Q + Q * D + np.arange(0, Q * D)] = np.log(np.ndarray.flatten(s)).T
```
to
```
hypinit[Q: Q + Q * D] = np.log(np.ndarray.flatten(m)).T        
hypinit[Q + Q * D: Q + 2*(Q * D)] = np.log(np.ndarray.flatten(s)).T
```

Now the code is running. Would you please carefully confirm that these changes are what is intended, that the indexing math is correct, and that they should working across platforms etc? Thanks a lot in advance.

The entire modified code piece is here:

```
def initSMhypers(self, x, y):
        """
        Initialize hyperparameters for the spectral-mixture kernel. Weights are
        all set to be uniformly distributed, means are given by a random sample
        from a uniform distribution scaled by the Nyquist frequency, and variances are given by a random sample from a uniform distribution scaled by the max distance.
        """
        x = np.atleast_2d(x)
        y = np.atleast_2d(y)
        (n, D) = x.shape
        Q = self.para[0]
        w = old_div(np.std(y), Q)
        m = np.ones((D, Q))
        s = np.ones((D, Q))
        hypinit = (Q + 2 * D * Q)*[1]

        for i in range(D):
            # Calculate distances
            xslice = np.atleast_2d(x[:, i]).T
            d2 = spdist.cdist(xslice, xslice, 'sqeuclidean')
            if n > 1:
                d2[d2 == 0] = d2[0, 1]
            else:
                d2[d2 == 0] = 1.0
                        
            minshift = np.maximum(np.min(np.min(np.sqrt(d2))),1e-6) 
            #minshift = np.max(np.min(np.min(np.sqrt(d2))),1e-6) 
            nyquist = old_div(0.5, minshift)
            m[i, :] = nyquist * np.random.ranf(Q)
            maxshift = np.minimum(np.max(np.max(np.sqrt(d2))),1e-6)
            #maxshift = np.min(np.max(np.max(np.sqrt(d2))),1e-6)
            s[i, :] = old_div(1., np.abs(maxshift * np.random.ranf(Q)))
        hypinit[:Q] = [np.log(w)] * Q 
        #hypinit[:Q] = np.log(w)       
   
        hypinit[Q: Q + Q * D] = np.log(np.ndarray.flatten(m)).T
        hypinit[Q + Q * D: Q + 2*(Q * D)] = np.log(np.ndarray.flatten(s)).T
        #hypinit[Q + np.arange(0, Q * D)] = np.log(np.ndarray.flatten(m)).T
        #hypinit[Q + Q * D + np.arange(0, Q * D)] = np.log(np.ndarray.flatten(s)).T
        self.hyp = hypinit
```

**Comment by mpzapf** [comment]
@mathDR 
Can confirm that including my changes there are still some inf's coming up in the hyperparameter intialization (not in minimal example, but for a data set with 10 dimensions), leading to the error:

```
Traceback (most recent call last):
  File "/usr/home/xyz/Research_Packages/pyGPs/pyGPs/Core/gp.py", line 341, in getPosterior
    post, nlZ, dnlZ = self.inffunc.evaluate(self.meanfunc, self.covfunc, self.likfunc, self.x, self.y, 3)
  File "/usr/home/xyz/Research_Packages/pyGPs/pyGPs/Core/inf.py", line 362, in evaluate
    L     = jitchol(old_div(K,sn2)+np.eye(n)).T            # Cholesky factor of covariance with noise
  File "/usr/home/xyz/Research_Packages/pyGPs/pyGPs/Core/tools.py", line 77, in jitchol
    raise np.linalg.LinAlgError("kernel matrix not positive definite, even with jitter.")
numpy.linalg.linalg.LinAlgError: kernel matrix not positive definite, even with jitter.
```

Maybe I got it wrong how generally maxshift and minshift work. Could you please shed light on this? Thanks in advance.

**Comment by mathDR** [comment]
hey @mpzapf I didn't have time to get to this today.  If you want to know how the initialization script works, you can look [here](https://people.orie.cornell.edu/andrew/code/#spectral) . The initialization is gone through in more detail.

I will hopefully be able to get to this over the weekend

**Comment by mpzapf** [comment]
Hi @mathDR , thanks for sending the link, I'll have a look at the initialization script, didn't have time till now. 
If you have time in the meantime to check whether my code modifications make sense, that would be great. 
[The prediction results I get after these modifications do not look right - comparing them with the outcome of cdipaolo's implementation of the SM kernel in GPy (https://github.com/SheffieldML/GPy/issues/401) - so I assume there might be some issue with my modifications or another part. That said, cdipaolo states that his implementation has problems with hyperparameter initialization, as well the model specification might differ in some aspect between libraries,  so I'm not entirely sure.]

Hope we can fix this to eventually get it working both in pyGPs and GPy! (happy to port the hyperparameter intialization to GPy later)

**Comment by jorgeloaiza** [comment]
Hello.
¿Could anybody help me with an error when i use Spectral Mixture kernel in pyGPs?
Error is just present when i use SM, not in others kernels.

import pyGPs
import numpy as np

xnew=np.linspace(1464,1487,24)
gpx_new = xnew.reshape(xnew.shape[0], 1)
gpx_new.shape

SM=pyGPs.cov.SM(Q=3,D=gpx.shape[1])
model = pyGPs.GPR() 
model.setPrior(mean=m,kernel=kernel) 
model.setData(gpx,gpy)
model.getPosterior()
model.optimize()
ym, ys2, fm, fs2, lp=model.predict(gpx_new)

The error is: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
